# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\"R\n\nVqaRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\x12\x0e\n\x06use_pm\x18\x03 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"A\n\x0bVqaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t21\n\nVqaService\x12#\n\x06\x61nswer\x12\x0b.VqaRequest\x1a\x0c.VqaResponseb\x06proto3')
)




_VQAREQUEST = _descriptor.Descriptor(
  name='VqaRequest',
  full_name='VqaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='VqaRequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_format', full_name='VqaRequest.image_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_pm', full_name='VqaRequest.use_pm', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='VqaRequest.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=99,
)


_VQARESPONSE = _descriptor.Descriptor(
  name='VqaResponse',
  full_name='VqaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='VqaResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ok', full_name='VqaResponse.ok', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='VqaResponse.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['VqaRequest'] = _VQAREQUEST
DESCRIPTOR.message_types_by_name['VqaResponse'] = _VQARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VqaRequest = _reflection.GeneratedProtocolMessageType('VqaRequest', (_message.Message,), dict(
  DESCRIPTOR = _VQAREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:VqaRequest)
  ))
_sym_db.RegisterMessage(VqaRequest)

VqaResponse = _reflection.GeneratedProtocolMessageType('VqaResponse', (_message.Message,), dict(
  DESCRIPTOR = _VQARESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:VqaResponse)
  ))
_sym_db.RegisterMessage(VqaResponse)



_VQASERVICE = _descriptor.ServiceDescriptor(
  name='VqaService',
  full_name='VqaService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=168,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='answer',
    full_name='VqaService.answer',
    index=0,
    containing_service=None,
    input_type=_VQAREQUEST,
    output_type=_VQARESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VQASERVICE)

DESCRIPTOR.services_by_name['VqaService'] = _VQASERVICE

# @@protoc_insertion_point(module_scope)
