# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class VqaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.answer = channel.unary_unary(
        '/VqaService/answer',
        request_serializer=service__pb2.VqaRequest.SerializeToString,
        response_deserializer=service__pb2.VqaResponse.FromString,
        )


class VqaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def answer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VqaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'answer': grpc.unary_unary_rpc_method_handler(
          servicer.answer,
          request_deserializer=service__pb2.VqaRequest.FromString,
          response_serializer=service__pb2.VqaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'VqaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
